### ISSUE TITLE
Question | Where does the firebase info go?

### ISSUE THREAD

**Issue by Cobwebster** [rwieruch/nextjs-firebase-authentication#8]
Hey,

It says to put the firebase info in next.config.js,

Am I suppose to just overwrite 

```
const nextConfig = {
  env: {
    FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
    FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL,
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID:
      process.env.FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
  },
};
```
Not sure, the provided keys firebase give you don't match,

apiKey.. etc.

**Comment by rwieruch** [comment]
Ah sorry, the config should go in a *.env* file like:

```
FIREBASE_API_KEY=abc
FIREBASE_AUTH_DOMAIN=123
...
```

**Comment by Cobwebster** [comment]
https://imgur.com/a/Egbv2Hm

Something like that? This seems very wrong :/

**Comment by rwieruch** [comment]
You create a file in your project's root folder with the name: *.env*

In this file, you put your credentials with the following syntax

```
FIREBASE_API_KEY=abc
FIREBASE_AUTH_DOMAIN=abc
FIREBASE_DATABASE_URL=abc
FIREBASE_PROJECT_ID=abc
FIREBASE_STORAGE_BUCKET=abc
FIREBASE_MESSAGING_SENDER_ID=abc
FIREBASE_APP_ID=abc
```

**Comment by rwieruch** [comment]
If it works for you, can you open a PR to enhance the README.md to clarify things there? @Cobwebster This would help others a lot I guess 🚀

**Comment by rwieruch** [comment]
Done by @adenj over here https://github.com/rwieruch/nextjs-firebase-authentication/pull/10
